name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-with-utests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - run: |
         ./project_1/gradlew test
